
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qitelgupnfdszpioxmnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpdGVsZ3VwbmZkc3pwaW94bW5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODc2MTMsImV4cCI6MjA2MTg2MzYxM30.Z9r3womzMxjVm7gFH8j4Wb1ZNWgMwubqBdkKtRcPGlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
